### ISSUE TITLE
Prepare a UI

### ISSUE THREAD

**Issue by mohsinansari0705** [mohsinansari0705/Voice-Activated-Virtual-Assistant#3]
Make a simple and basic UI for the interface of the web app like chatGPT home page, In this remove the typing section.

**Comment by snehautekar05** [comment]
Hey @mohsinansari0705  can you assign this issue to me?

**Comment by snehautekar05** [comment]
Hey @mohsinansari0705 I have sent the PR request pls check it....

**Comment by mohsinansari0705** [comment]
@snehautekar05 As you have recently pull your changes but due to some sort of issues, I have close your PR.
I review your contribution and glad to say that it a awesome.

Now you have to make a new PR to be merged to resolve this issue.
