### ISSUE TITLE
⭐ Integrate OpenAI

### ISSUE THREAD

**Issue by mohsinansari0705** [mohsinansari0705/Voice-Activated-Virtual-Assistant#6]
# Files
create a .json file with the integration of OpenAI API key for those commands which are not processed by our assistant.
We do this to get the response when our assistant can't process the commands.

**Comment by vp007-dev** [comment]
But api key is not free forever it will be exauhsted after some time and ask for recharge

**Comment by vp007-dev** [comment]
If u have bought one then i can work on it

**Comment by mohsinansari0705** [comment]
no need to purchase the api key simply write the code snippet for openAI API integration in the assistant and leave the actual api key as blank.
We take care of it in actual deployment time.
