### ISSUE TITLE
⭐⭐ Add Features ⭐⭐

### ISSUE THREAD

**Issue by mohsinansari0705** [mohsinansari0705/Voice-Activated-Virtual-Assistant#7]
# Add
Add your liked features to make the assistant more efficient.
Try to deal with big one, and get to the solution with our community.

# Integrate
Integrate something which you like and make the assistant more vibrant like by adding news, to-do's, voice-calculator, storyteller, fun facts and many more which vibrate in your mind.

**Comment by DarkZelda11** [comment]
Hi moshsinansari0705, I am an upcoming programmer currently studying for my certification. As part of the criteria to receive my qualification, I must contribute to an open-source project like yours. I like your project's look and wish to collaborate on it. I would greatly appreciate it if you could assign this issue to me.

Some suggestions that I can think of implementing in this project include a list of command shortcuts, greetings that are customized for the user and overall UI improvements.

Thank you in advance.
